name: briskers_app
description: Briskers auto repair office and owner app
publish_to: none
version: 0.10.1+1010

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  package_info_plus: ^8.3.1
  image_picker: ^1.2.0
  image: ^4.10.1
  mobile_scanner: ^7.4.2
  supabase_flutter: ^2.17.2
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.5
  drift: 2.32.1
  drift_flutter: 0.3.1
  path_provider: 2.1.5
  workmanager: ^0.10.10
  saf: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.15.1
  drift_dev: 2.32.1

flutter:
  uses-material-design: true
  assets:
    - assets/job_car_watermark.png
    - assets/briskers_header_logo.png
    - assets/home_car.png
